#!/usr/bin/env bash

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure custom header in Nginx
sudo sed -i '/listen 80 default_server;/a \ \ \ \ add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
