#!/usr/bin/env bash
# Debugging task number 2 on connection failed to port 80
sudo ln -s --force /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
