#!/usr/bin/env bash
#Requirements:
#    Your Bash script must be 7 lines long or less
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod +rw /etc/nginx/nginx.conf
pkill apache2
su -c 'service nginx start' nginx
